#!/bin/sh

set -e

# The ppb[ew]d scripts generated by install4j contain commands that are run based on
# the arguments passed to them. Those commands that actually start a service contain
# double zeroes followed by a classpath url beginning with "com.cyberpowersystems"
# These zeroes represent the file that standard error is sent to, and the file that
# standard out is sent to, respectively.
# We can replace them with dated file names to save the output using sed:
#	Old cmd: $some_long_java_command 0 0 com.cyberpowersystems...
#	New cmd: $some_long_java_command stderr stdout com.cyberpowersystems...
if [ "$ENABLE_LOGGING" = true ] ; then
	# see: https://stackoverflow.com/a/21210966
	sed -E -i -e "s#0 0 com.cyberpowersystems#\$prg_dir/log/\$\(date +\"%Y-%m-%d_%H-%M-%S\"\)_\${progname}_err.log \$prg_dir/log/\$\(date +\"%Y-%m-%d_%H-%M-%S\"\)_\${progname}_out.log com.cyberpowersystems#g" /usr/local/PPB/ppbd
	sed -E -i -e "s#0 0 com.cyberpowersystems#\$prg_dir/log/\$\(date +\"%Y-%m-%d_%H-%M-%S\"\)_\${progname}_err.log \$prg_dir/log/\$\(date +\"%Y-%m-%d_%H-%M-%S\"\)_\${progname}_out.log com.cyberpowersystems#g" /usr/local/PPB/ppbwd
fi

service ppbd start
service ppbwd start

# to run indefinitely instead of stopping as soon as the previous commands complete
tail -F /dev/null
