version: '3'

services:
  app:
    image: ghcr.io/nathanvaughn/powerpanel-business:local-latest
    # build: .
    ports:
      - 80:3052
    privileged: true
    restart: unless-stopped
    volumes:
      - app_data:/usr/local/PPB/db_local/
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone

volumes:
  app_data:
    driver: local
