version: '3'

services:
  app:
    image: ghcr.io/nathanvaughn/powerpanel-business:local-latest
    # build: .
    ports:
      # Ports: ???, http, https, ???, snmp, snmp
      # See https://dl4jz3rbrsfum.cloudfront.net/documents/CyberPower_UM_PowerPanel-Business-481.pdf
      - 2003:2003
      - 3052:3052
      - 53568:53568/tcp
      - 53566:53566/udp
      - 161:161/udp
      - 162:162/udp
    devices:
      # sharing /dev/usb is sufficient for debian bullseye,
      # but other debian-based distributions might also 
      # need access to /dev/bus/usb/*
      - "/dev/usb:/dev/usb"
#      - "/dev/bus/usb:/dev/bus/usb"
    restart: unless-stopped
    volumes:
      - app_data:/usr/local/PPB
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

volumes:
  app_data:
    driver: local
