#!/bin/sh
# every command line in the ppb[ew]d scripts generated by install4j that start the service
# contains double zeroes followed by a classpath url beginning with "com.cyberpowersystems"
# These zeroes represent the file to direct standard error and standard out to, respectively.
# We can replace them with dated file names to save the output:
sed -E -i -e "s#0 0 com.cyberpowersystems#\$prg_dir/log/\$\(date +\"%Y-%m-%d_%H-%M-%S\"\)_\${progname}_err.log \$prg_dir/log/\$\(date +\"%Y-%m-%d_%H-%M-%S\"\)_\${progname}_out.log com.cyberpowersystems#g" /usr/local/PPB/ppbed
sed -E -i -e "s#0 0 com.cyberpowersystems#\$prg_dir/log/\$\(date +\"%Y-%m-%d_%H-%M-%S\"\)_\${progname}_err.log \$prg_dir/log/\$\(date +\"%Y-%m-%d_%H-%M-%S\"\)_\${progname}_out.log com.cyberpowersystems#g" /usr/local/PPB/ppbwd

service ppbed start
service ppbwd start

# to run indefinitely instead of stopping as soon as the previous commands complete
tail -F /dev/null
